---
- name: install packages
  apt: name={{ item }} update_cache=yes
  with_items:
    - mysql-server
    - python-mysqldb

- name: mysql listening on all ports
  lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address line="bind-address = 0.0.0.0"
  notify: restart mysql

- name: starting mysql service and enabling it at startup
  service: name=mysql state=started enabled=yes

- name: configure demo database
  mysql_db: name=demo state=present

- name: create demo user
  mysql_user: name=demo password=demo priv=demo.*:ALL host='%' state=present
