---
- hosts: loadbalancer
  become: yes
  tasks:
    - name: nginx status
      shell: service nginx status

    - name: verify ngnix is listening on port 80
      wait_for: port=80 timeout=1

- hosts: webserver
  become: yes
  tasks:
    - name: apache2 status
      shell: service apache2 status
    
    - name: verify apache is listening on port 80
      wait_for: port=80 timeout=1

- hosts: database
  become: yes
  tasks:
    - name: mysql status
      shell: service mysql status

    - name: verify mysql is listening on port 3306
      wait_for: port=3306 timeout=1
